/* soapServerAPIBindingProxy.cpp
   Generated by gSOAP 2.8.16 from ServerAPI.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "stdafx.h"
#include "ServerAPIBindingProxy.h"

ServerAPIBindingProxy::ServerAPIBindingProxy()
{	this->soap = soap_new();
	this->own = true;
	ServerAPIBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

ServerAPIBindingProxy::ServerAPIBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->own = false;
	ServerAPIBindingProxy_init(_soap->imode, _soap->omode);
}

ServerAPIBindingProxy::ServerAPIBindingProxy(const char *url)
{	this->soap = soap_new();
	this->own = true;
	ServerAPIBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

ServerAPIBindingProxy::ServerAPIBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	ServerAPIBindingProxy_init(iomode, iomode);
}

ServerAPIBindingProxy::ServerAPIBindingProxy(const char *url, soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	ServerAPIBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

ServerAPIBindingProxy::ServerAPIBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->own = true;
	ServerAPIBindingProxy_init(imode, omode);
}

ServerAPIBindingProxy::~ServerAPIBindingProxy()
{	if (this->own)
		soap_free(this->soap);
}

void ServerAPIBindingProxy::ServerAPIBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://stub.service.wfe.runa.ru/", NULL, NULL},
	{"ns1", "http://impl.service.wfe.runa.ru/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void ServerAPIBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void ServerAPIBindingProxy::reset()
{	destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	ServerAPIBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void ServerAPIBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

const SOAP_ENV__Header *ServerAPIBindingProxy::soap_header()
{	return this->soap->header;
}

const SOAP_ENV__Fault *ServerAPIBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *ServerAPIBindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *ServerAPIBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int ServerAPIBindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int ServerAPIBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void ServerAPIBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void ServerAPIBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *ServerAPIBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int ServerAPIBindingProxy::authenticateByCallerPrincipal(const char *endpoint, const char *soap_action, ns1__authenticateByCallerPrincipal *ns1__authenticateByCallerPrincipal_, ns1__authenticateByCallerPrincipalResponse *ns1__authenticateByCallerPrincipalResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__authenticateByCallerPrincipal soap_tmp___ns1__authenticateByCallerPrincipal;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__authenticateByCallerPrincipal.ns1__authenticateByCallerPrincipal_ = ns1__authenticateByCallerPrincipal_;
	soap_serializeheader(soap);
	soap_serialize___ns1__authenticateByCallerPrincipal(soap, &soap_tmp___ns1__authenticateByCallerPrincipal);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__authenticateByCallerPrincipal(soap, &soap_tmp___ns1__authenticateByCallerPrincipal, "-ns1:authenticateByCallerPrincipal", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__authenticateByCallerPrincipal(soap, &soap_tmp___ns1__authenticateByCallerPrincipal, "-ns1:authenticateByCallerPrincipal", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__authenticateByCallerPrincipalResponse_)
		return soap_closesock(soap);
	ns1__authenticateByCallerPrincipalResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__authenticateByCallerPrincipalResponse_->soap_get(soap, "ns1:authenticateByCallerPrincipalResponse", "ns1:authenticateByCallerPrincipalResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::authenticateByKerberos(const char *endpoint, const char *soap_action, ns1__authenticateByKerberos *ns1__authenticateByKerberos_, ns1__authenticateByKerberosResponse *ns1__authenticateByKerberosResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__authenticateByKerberos soap_tmp___ns1__authenticateByKerberos;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__authenticateByKerberos.ns1__authenticateByKerberos_ = ns1__authenticateByKerberos_;
	soap_serializeheader(soap);
	soap_serialize___ns1__authenticateByKerberos(soap, &soap_tmp___ns1__authenticateByKerberos);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__authenticateByKerberos(soap, &soap_tmp___ns1__authenticateByKerberos, "-ns1:authenticateByKerberos", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__authenticateByKerberos(soap, &soap_tmp___ns1__authenticateByKerberos, "-ns1:authenticateByKerberos", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__authenticateByKerberosResponse_)
		return soap_closesock(soap);
	ns1__authenticateByKerberosResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__authenticateByKerberosResponse_->soap_get(soap, "ns1:authenticateByKerberosResponse", "ns1:authenticateByKerberosResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::authenticateByLoginPassword(const char *endpoint, const char *soap_action, ns1__authenticateByLoginPassword *ns1__authenticateByLoginPassword_, ns1__authenticateByLoginPasswordResponse *ns1__authenticateByLoginPasswordResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__authenticateByLoginPassword soap_tmp___ns1__authenticateByLoginPassword;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__authenticateByLoginPassword.ns1__authenticateByLoginPassword_ = ns1__authenticateByLoginPassword_;
	soap_serializeheader(soap);
	soap_serialize___ns1__authenticateByLoginPassword(soap, &soap_tmp___ns1__authenticateByLoginPassword);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__authenticateByLoginPassword(soap, &soap_tmp___ns1__authenticateByLoginPassword, "-ns1:authenticateByLoginPassword", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__authenticateByLoginPassword(soap, &soap_tmp___ns1__authenticateByLoginPassword, "-ns1:authenticateByLoginPassword", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__authenticateByLoginPasswordResponse_)
		return soap_closesock(soap);
	ns1__authenticateByLoginPasswordResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__authenticateByLoginPasswordResponse_->soap_get(soap, "ns1:authenticateByLoginPasswordResponse", "ns1:authenticateByLoginPasswordResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::assignSwimlane(const char *endpoint, const char *soap_action, ns1__assignSwimlane *ns1__assignSwimlane_, ns1__assignSwimlaneResponse *ns1__assignSwimlaneResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__assignSwimlane soap_tmp___ns1__assignSwimlane;
	struct __ns1__assignSwimlaneResponse *soap_tmp___ns1__assignSwimlaneResponse;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__assignSwimlane.ns1__assignSwimlane_ = ns1__assignSwimlane_;
	soap_serializeheader(soap);
	soap_serialize___ns1__assignSwimlane(soap, &soap_tmp___ns1__assignSwimlane);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__assignSwimlane(soap, &soap_tmp___ns1__assignSwimlane, "-ns1:assignSwimlane", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__assignSwimlane(soap, &soap_tmp___ns1__assignSwimlane, "-ns1:assignSwimlane", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__assignSwimlaneResponse_)
		return soap_closesock(soap);
	ns1__assignSwimlaneResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___ns1__assignSwimlaneResponse = soap_get___ns1__assignSwimlaneResponse(soap, NULL, "-ns1:assignSwimlaneResponse", "ns1:assignSwimlaneResponse");
	if (!soap_tmp___ns1__assignSwimlaneResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ns1__assignSwimlaneResponse_ && soap_tmp___ns1__assignSwimlaneResponse->ns1__assignSwimlaneResponse_)
		*ns1__assignSwimlaneResponse_ = *soap_tmp___ns1__assignSwimlaneResponse->ns1__assignSwimlaneResponse_;
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::assignTask(const char *endpoint, const char *soap_action, ns1__assignTask *ns1__assignTask_, ns1__assignTaskResponse *ns1__assignTaskResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__assignTask soap_tmp___ns1__assignTask;
	struct __ns1__assignTaskResponse *soap_tmp___ns1__assignTaskResponse;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__assignTask.ns1__assignTask_ = ns1__assignTask_;
	soap_serializeheader(soap);
	soap_serialize___ns1__assignTask(soap, &soap_tmp___ns1__assignTask);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__assignTask(soap, &soap_tmp___ns1__assignTask, "-ns1:assignTask", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__assignTask(soap, &soap_tmp___ns1__assignTask, "-ns1:assignTask", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__assignTaskResponse_)
		return soap_closesock(soap);
	ns1__assignTaskResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___ns1__assignTaskResponse = soap_get___ns1__assignTaskResponse(soap, NULL, "-ns1:assignTaskResponse", "ns1:assignTaskResponse");
	if (!soap_tmp___ns1__assignTaskResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ns1__assignTaskResponse_ && soap_tmp___ns1__assignTaskResponse->ns1__assignTaskResponse_)
		*ns1__assignTaskResponse_ = *soap_tmp___ns1__assignTaskResponse->ns1__assignTaskResponse_;
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::cancelProcess(const char *endpoint, const char *soap_action, ns1__cancelProcess *ns1__cancelProcess_, ns1__cancelProcessResponse *ns1__cancelProcessResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__cancelProcess soap_tmp___ns1__cancelProcess;
	struct __ns1__cancelProcessResponse *soap_tmp___ns1__cancelProcessResponse;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__cancelProcess.ns1__cancelProcess_ = ns1__cancelProcess_;
	soap_serializeheader(soap);
	soap_serialize___ns1__cancelProcess(soap, &soap_tmp___ns1__cancelProcess);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__cancelProcess(soap, &soap_tmp___ns1__cancelProcess, "-ns1:cancelProcess", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__cancelProcess(soap, &soap_tmp___ns1__cancelProcess, "-ns1:cancelProcess", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__cancelProcessResponse_)
		return soap_closesock(soap);
	ns1__cancelProcessResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___ns1__cancelProcessResponse = soap_get___ns1__cancelProcessResponse(soap, NULL, "-ns1:cancelProcessResponse", "ns1:cancelProcessResponse");
	if (!soap_tmp___ns1__cancelProcessResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ns1__cancelProcessResponse_ && soap_tmp___ns1__cancelProcessResponse->ns1__cancelProcessResponse_)
		*ns1__cancelProcessResponse_ = *soap_tmp___ns1__cancelProcessResponse->ns1__cancelProcessResponse_;
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::completeTaskWS(const char *endpoint, const char *soap_action, ns1__completeTaskWS *ns1__completeTaskWS_, ns1__completeTaskWSResponse *ns1__completeTaskWSResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__completeTaskWS soap_tmp___ns1__completeTaskWS;
	struct __ns1__completeTaskWSResponse *soap_tmp___ns1__completeTaskWSResponse;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__completeTaskWS.ns1__completeTaskWS_ = ns1__completeTaskWS_;
	soap_serializeheader(soap);
	soap_serialize___ns1__completeTaskWS(soap, &soap_tmp___ns1__completeTaskWS);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__completeTaskWS(soap, &soap_tmp___ns1__completeTaskWS, "-ns1:completeTaskWS", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__completeTaskWS(soap, &soap_tmp___ns1__completeTaskWS, "-ns1:completeTaskWS", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__completeTaskWSResponse_)
		return soap_closesock(soap);
	ns1__completeTaskWSResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___ns1__completeTaskWSResponse = soap_get___ns1__completeTaskWSResponse(soap, NULL, "-ns1:completeTaskWSResponse", "ns1:completeTaskWSResponse");
	if (!soap_tmp___ns1__completeTaskWSResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ns1__completeTaskWSResponse_ && soap_tmp___ns1__completeTaskWSResponse->ns1__completeTaskWSResponse_)
		*ns1__completeTaskWSResponse_ = *soap_tmp___ns1__completeTaskWSResponse->ns1__completeTaskWSResponse_;
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getParentProcess(const char *endpoint, const char *soap_action, ns1__getParentProcess *ns1__getParentProcess_, ns1__getParentProcessResponse *ns1__getParentProcessResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getParentProcess soap_tmp___ns1__getParentProcess;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getParentProcess.ns1__getParentProcess_ = ns1__getParentProcess_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getParentProcess(soap, &soap_tmp___ns1__getParentProcess);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getParentProcess(soap, &soap_tmp___ns1__getParentProcess, "-ns1:getParentProcess", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getParentProcess(soap, &soap_tmp___ns1__getParentProcess, "-ns1:getParentProcess", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getParentProcessResponse_)
		return soap_closesock(soap);
	ns1__getParentProcessResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getParentProcessResponse_->soap_get(soap, "ns1:getParentProcessResponse", "ns1:getParentProcessResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getProcess(const char *endpoint, const char *soap_action, ns1__getProcess *ns1__getProcess_, ns1__getProcessResponse *ns1__getProcessResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getProcess soap_tmp___ns1__getProcess;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getProcess.ns1__getProcess_ = ns1__getProcess_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getProcess(soap, &soap_tmp___ns1__getProcess);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getProcess(soap, &soap_tmp___ns1__getProcess, "-ns1:getProcess", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getProcess(soap, &soap_tmp___ns1__getProcess, "-ns1:getProcess", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getProcessResponse_)
		return soap_closesock(soap);
	ns1__getProcessResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getProcessResponse_->soap_get(soap, "ns1:getProcessResponse", "ns1:getProcessResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getProcessDiagram(const char *endpoint, const char *soap_action, ns1__getProcessDiagram *ns1__getProcessDiagram_, ns1__getProcessDiagramResponse *ns1__getProcessDiagramResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getProcessDiagram soap_tmp___ns1__getProcessDiagram;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getProcessDiagram.ns1__getProcessDiagram_ = ns1__getProcessDiagram_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getProcessDiagram(soap, &soap_tmp___ns1__getProcessDiagram);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getProcessDiagram(soap, &soap_tmp___ns1__getProcessDiagram, "-ns1:getProcessDiagram", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getProcessDiagram(soap, &soap_tmp___ns1__getProcessDiagram, "-ns1:getProcessDiagram", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getProcessDiagramResponse_)
		return soap_closesock(soap);
	ns1__getProcessDiagramResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getProcessDiagramResponse_->soap_get(soap, "ns1:getProcessDiagramResponse", "ns1:getProcessDiagramResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getProcessDiagramElements(const char *endpoint, const char *soap_action, ns1__getProcessDiagramElements *ns1__getProcessDiagramElements_, ns1__getProcessDiagramElementsResponse *ns1__getProcessDiagramElementsResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getProcessDiagramElements soap_tmp___ns1__getProcessDiagramElements;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getProcessDiagramElements.ns1__getProcessDiagramElements_ = ns1__getProcessDiagramElements_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getProcessDiagramElements(soap, &soap_tmp___ns1__getProcessDiagramElements);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getProcessDiagramElements(soap, &soap_tmp___ns1__getProcessDiagramElements, "-ns1:getProcessDiagramElements", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getProcessDiagramElements(soap, &soap_tmp___ns1__getProcessDiagramElements, "-ns1:getProcessDiagramElements", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getProcessDiagramElementsResponse_)
		return soap_closesock(soap);
	ns1__getProcessDiagramElementsResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getProcessDiagramElementsResponse_->soap_get(soap, "ns1:getProcessDiagramElementsResponse", "ns1:getProcessDiagramElementsResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getProcessHistoryDiagram(const char *endpoint, const char *soap_action, ns1__getProcessHistoryDiagram *ns1__getProcessHistoryDiagram_, ns1__getProcessHistoryDiagramResponse *ns1__getProcessHistoryDiagramResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getProcessHistoryDiagram soap_tmp___ns1__getProcessHistoryDiagram;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getProcessHistoryDiagram.ns1__getProcessHistoryDiagram_ = ns1__getProcessHistoryDiagram_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getProcessHistoryDiagram(soap, &soap_tmp___ns1__getProcessHistoryDiagram);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getProcessHistoryDiagram(soap, &soap_tmp___ns1__getProcessHistoryDiagram, "-ns1:getProcessHistoryDiagram", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getProcessHistoryDiagram(soap, &soap_tmp___ns1__getProcessHistoryDiagram, "-ns1:getProcessHistoryDiagram", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getProcessHistoryDiagramResponse_)
		return soap_closesock(soap);
	ns1__getProcessHistoryDiagramResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getProcessHistoryDiagramResponse_->soap_get(soap, "ns1:getProcessHistoryDiagramResponse", "ns1:getProcessHistoryDiagramResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getProcessHistoryDiagramElements(const char *endpoint, const char *soap_action, ns1__getProcessHistoryDiagramElements *ns1__getProcessHistoryDiagramElements_, ns1__getProcessHistoryDiagramElementsResponse *ns1__getProcessHistoryDiagramElementsResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getProcessHistoryDiagramElements soap_tmp___ns1__getProcessHistoryDiagramElements;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getProcessHistoryDiagramElements.ns1__getProcessHistoryDiagramElements_ = ns1__getProcessHistoryDiagramElements_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getProcessHistoryDiagramElements(soap, &soap_tmp___ns1__getProcessHistoryDiagramElements);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getProcessHistoryDiagramElements(soap, &soap_tmp___ns1__getProcessHistoryDiagramElements, "-ns1:getProcessHistoryDiagramElements", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getProcessHistoryDiagramElements(soap, &soap_tmp___ns1__getProcessHistoryDiagramElements, "-ns1:getProcessHistoryDiagramElements", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getProcessHistoryDiagramElementsResponse_)
		return soap_closesock(soap);
	ns1__getProcessHistoryDiagramElementsResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getProcessHistoryDiagramElementsResponse_->soap_get(soap, "ns1:getProcessHistoryDiagramElementsResponse", "ns1:getProcessHistoryDiagramElementsResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getProcessLogValue(const char *endpoint, const char *soap_action, ns1__getProcessLogValue *ns1__getProcessLogValue_, ns1__getProcessLogValueResponse *ns1__getProcessLogValueResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getProcessLogValue soap_tmp___ns1__getProcessLogValue;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getProcessLogValue.ns1__getProcessLogValue_ = ns1__getProcessLogValue_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getProcessLogValue(soap, &soap_tmp___ns1__getProcessLogValue);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getProcessLogValue(soap, &soap_tmp___ns1__getProcessLogValue, "-ns1:getProcessLogValue", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getProcessLogValue(soap, &soap_tmp___ns1__getProcessLogValue, "-ns1:getProcessLogValue", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getProcessLogValueResponse_)
		return soap_closesock(soap);
	ns1__getProcessLogValueResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getProcessLogValueResponse_->soap_get(soap, "ns1:getProcessLogValueResponse", "ns1:getProcessLogValueResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getProcessLogs(const char *endpoint, const char *soap_action, ns1__getProcessLogs *ns1__getProcessLogs_, ns1__getProcessLogsResponse *ns1__getProcessLogsResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getProcessLogs soap_tmp___ns1__getProcessLogs;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getProcessLogs.ns1__getProcessLogs_ = ns1__getProcessLogs_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getProcessLogs(soap, &soap_tmp___ns1__getProcessLogs);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getProcessLogs(soap, &soap_tmp___ns1__getProcessLogs, "-ns1:getProcessLogs", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getProcessLogs(soap, &soap_tmp___ns1__getProcessLogs, "-ns1:getProcessLogs", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getProcessLogsResponse_)
		return soap_closesock(soap);
	ns1__getProcessLogsResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getProcessLogsResponse_->soap_get(soap, "ns1:getProcessLogsResponse", "ns1:getProcessLogsResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getProcessTasks(const char *endpoint, const char *soap_action, ns1__getProcessTasks *ns1__getProcessTasks_, ns1__getProcessTasksResponse *ns1__getProcessTasksResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getProcessTasks soap_tmp___ns1__getProcessTasks;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getProcessTasks.ns1__getProcessTasks_ = ns1__getProcessTasks_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getProcessTasks(soap, &soap_tmp___ns1__getProcessTasks);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getProcessTasks(soap, &soap_tmp___ns1__getProcessTasks, "-ns1:getProcessTasks", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getProcessTasks(soap, &soap_tmp___ns1__getProcessTasks, "-ns1:getProcessTasks", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getProcessTasksResponse_)
		return soap_closesock(soap);
	ns1__getProcessTasksResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getProcessTasksResponse_->soap_get(soap, "ns1:getProcessTasksResponse", "ns1:getProcessTasksResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getProcesses(const char *endpoint, const char *soap_action, ns1__getProcesses *ns1__getProcesses_, ns1__getProcessesResponse *ns1__getProcessesResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getProcesses soap_tmp___ns1__getProcesses;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getProcesses.ns1__getProcesses_ = ns1__getProcesses_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getProcesses(soap, &soap_tmp___ns1__getProcesses);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getProcesses(soap, &soap_tmp___ns1__getProcesses, "-ns1:getProcesses", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getProcesses(soap, &soap_tmp___ns1__getProcesses, "-ns1:getProcesses", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getProcessesResponse_)
		return soap_closesock(soap);
	ns1__getProcessesResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getProcessesResponse_->soap_get(soap, "ns1:getProcessesResponse", "ns1:getProcessesResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getProcessesByFilter(const char *endpoint, const char *soap_action, ns1__getProcessesByFilter *ns1__getProcessesByFilter_, ns1__getProcessesByFilterResponse *ns1__getProcessesByFilterResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getProcessesByFilter soap_tmp___ns1__getProcessesByFilter;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getProcessesByFilter.ns1__getProcessesByFilter_ = ns1__getProcessesByFilter_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getProcessesByFilter(soap, &soap_tmp___ns1__getProcessesByFilter);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getProcessesByFilter(soap, &soap_tmp___ns1__getProcessesByFilter, "-ns1:getProcessesByFilter", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getProcessesByFilter(soap, &soap_tmp___ns1__getProcessesByFilter, "-ns1:getProcessesByFilter", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getProcessesByFilterResponse_)
		return soap_closesock(soap);
	ns1__getProcessesByFilterResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getProcessesByFilterResponse_->soap_get(soap, "ns1:getProcessesByFilterResponse", "ns1:getProcessesByFilterResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getProcessesCount(const char *endpoint, const char *soap_action, ns1__getProcessesCount *ns1__getProcessesCount_, ns1__getProcessesCountResponse *ns1__getProcessesCountResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getProcessesCount soap_tmp___ns1__getProcessesCount;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getProcessesCount.ns1__getProcessesCount_ = ns1__getProcessesCount_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getProcessesCount(soap, &soap_tmp___ns1__getProcessesCount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getProcessesCount(soap, &soap_tmp___ns1__getProcessesCount, "-ns1:getProcessesCount", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getProcessesCount(soap, &soap_tmp___ns1__getProcessesCount, "-ns1:getProcessesCount", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getProcessesCountResponse_)
		return soap_closesock(soap);
	ns1__getProcessesCountResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getProcessesCountResponse_->soap_get(soap, "ns1:getProcessesCountResponse", "ns1:getProcessesCountResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getSubprocesses(const char *endpoint, const char *soap_action, ns1__getSubprocesses *ns1__getSubprocesses_, ns1__getSubprocessesResponse *ns1__getSubprocessesResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getSubprocesses soap_tmp___ns1__getSubprocesses;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getSubprocesses.ns1__getSubprocesses_ = ns1__getSubprocesses_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getSubprocesses(soap, &soap_tmp___ns1__getSubprocesses);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getSubprocesses(soap, &soap_tmp___ns1__getSubprocesses, "-ns1:getSubprocesses", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getSubprocesses(soap, &soap_tmp___ns1__getSubprocesses, "-ns1:getSubprocesses", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSubprocessesResponse_)
		return soap_closesock(soap);
	ns1__getSubprocessesResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getSubprocessesResponse_->soap_get(soap, "ns1:getSubprocessesResponse", "ns1:getSubprocessesResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getSwimlanes(const char *endpoint, const char *soap_action, ns1__getSwimlanes *ns1__getSwimlanes_, ns1__getSwimlanesResponse *ns1__getSwimlanesResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getSwimlanes soap_tmp___ns1__getSwimlanes;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getSwimlanes.ns1__getSwimlanes_ = ns1__getSwimlanes_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getSwimlanes(soap, &soap_tmp___ns1__getSwimlanes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getSwimlanes(soap, &soap_tmp___ns1__getSwimlanes, "-ns1:getSwimlanes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getSwimlanes(soap, &soap_tmp___ns1__getSwimlanes, "-ns1:getSwimlanes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSwimlanesResponse_)
		return soap_closesock(soap);
	ns1__getSwimlanesResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getSwimlanesResponse_->soap_get(soap, "ns1:getSwimlanesResponse", "ns1:getSwimlanesResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getSystemLogs(const char *endpoint, const char *soap_action, ns1__getSystemLogs *ns1__getSystemLogs_, ns1__getSystemLogsResponse *ns1__getSystemLogsResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getSystemLogs soap_tmp___ns1__getSystemLogs;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getSystemLogs.ns1__getSystemLogs_ = ns1__getSystemLogs_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getSystemLogs(soap, &soap_tmp___ns1__getSystemLogs);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getSystemLogs(soap, &soap_tmp___ns1__getSystemLogs, "-ns1:getSystemLogs", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getSystemLogs(soap, &soap_tmp___ns1__getSystemLogs, "-ns1:getSystemLogs", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSystemLogsResponse_)
		return soap_closesock(soap);
	ns1__getSystemLogsResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getSystemLogsResponse_->soap_get(soap, "ns1:getSystemLogsResponse", "ns1:getSystemLogsResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getSystemLogsCount(const char *endpoint, const char *soap_action, ns1__getSystemLogsCount *ns1__getSystemLogsCount_, ns1__getSystemLogsCountResponse *ns1__getSystemLogsCountResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getSystemLogsCount soap_tmp___ns1__getSystemLogsCount;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getSystemLogsCount.ns1__getSystemLogsCount_ = ns1__getSystemLogsCount_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getSystemLogsCount(soap, &soap_tmp___ns1__getSystemLogsCount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getSystemLogsCount(soap, &soap_tmp___ns1__getSystemLogsCount, "-ns1:getSystemLogsCount", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getSystemLogsCount(soap, &soap_tmp___ns1__getSystemLogsCount, "-ns1:getSystemLogsCount", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSystemLogsCountResponse_)
		return soap_closesock(soap);
	ns1__getSystemLogsCountResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getSystemLogsCountResponse_->soap_get(soap, "ns1:getSystemLogsCountResponse", "ns1:getSystemLogsCountResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getTask(const char *endpoint, const char *soap_action, ns1__getTask *ns1__getTask_, ns1__getTaskResponse *ns1__getTaskResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getTask soap_tmp___ns1__getTask;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getTask.ns1__getTask_ = ns1__getTask_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getTask(soap, &soap_tmp___ns1__getTask);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getTask(soap, &soap_tmp___ns1__getTask, "-ns1:getTask", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getTask(soap, &soap_tmp___ns1__getTask, "-ns1:getTask", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getTaskResponse_)
		return soap_closesock(soap);
	ns1__getTaskResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getTaskResponse_->soap_get(soap, "ns1:getTaskResponse", "ns1:getTaskResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getTasks(const char *endpoint, const char *soap_action, ns1__getTasks *ns1__getTasks_, ns1__getTasksResponse *ns1__getTasksResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getTasks soap_tmp___ns1__getTasks;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getTasks.ns1__getTasks_ = ns1__getTasks_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getTasks(soap, &soap_tmp___ns1__getTasks);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getTasks(soap, &soap_tmp___ns1__getTasks, "-ns1:getTasks", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getTasks(soap, &soap_tmp___ns1__getTasks, "-ns1:getTasks", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getTasksResponse_)
		return soap_closesock(soap);
	ns1__getTasksResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getTasksResponse_->soap_get(soap, "ns1:getTasksResponse", "ns1:getTasksResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getVariable(const char *endpoint, const char *soap_action, ns1__getVariable *ns1__getVariable_, ns1__getVariableResponse *ns1__getVariableResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getVariable soap_tmp___ns1__getVariable;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getVariable.ns1__getVariable_ = ns1__getVariable_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getVariable(soap, &soap_tmp___ns1__getVariable);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getVariable(soap, &soap_tmp___ns1__getVariable, "-ns1:getVariable", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getVariable(soap, &soap_tmp___ns1__getVariable, "-ns1:getVariable", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getVariableResponse_)
		return soap_closesock(soap);
	ns1__getVariableResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getVariableResponse_->soap_get(soap, "ns1:getVariableResponse", "ns1:getVariableResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::getVariablesWS(const char *endpoint, const char *soap_action, ns1__getVariablesWS *ns1__getVariablesWS_, ns1__getVariablesWSResponse *ns1__getVariablesWSResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__getVariablesWS soap_tmp___ns1__getVariablesWS;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getVariablesWS.ns1__getVariablesWS_ = ns1__getVariablesWS_;
	soap_serializeheader(soap);
	soap_serialize___ns1__getVariablesWS(soap, &soap_tmp___ns1__getVariablesWS);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getVariablesWS(soap, &soap_tmp___ns1__getVariablesWS, "-ns1:getVariablesWS", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getVariablesWS(soap, &soap_tmp___ns1__getVariablesWS, "-ns1:getVariablesWS", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getVariablesWSResponse_)
		return soap_closesock(soap);
	ns1__getVariablesWSResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getVariablesWSResponse_->soap_get(soap, "ns1:getVariablesWSResponse", "ns1:getVariablesWSResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::markTaskOpened(const char *endpoint, const char *soap_action, ns1__markTaskOpened *ns1__markTaskOpened_, ns1__markTaskOpenedResponse *ns1__markTaskOpenedResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__markTaskOpened soap_tmp___ns1__markTaskOpened;
	struct __ns1__markTaskOpenedResponse *soap_tmp___ns1__markTaskOpenedResponse;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__markTaskOpened.ns1__markTaskOpened_ = ns1__markTaskOpened_;
	soap_serializeheader(soap);
	soap_serialize___ns1__markTaskOpened(soap, &soap_tmp___ns1__markTaskOpened);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__markTaskOpened(soap, &soap_tmp___ns1__markTaskOpened, "-ns1:markTaskOpened", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__markTaskOpened(soap, &soap_tmp___ns1__markTaskOpened, "-ns1:markTaskOpened", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__markTaskOpenedResponse_)
		return soap_closesock(soap);
	ns1__markTaskOpenedResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___ns1__markTaskOpenedResponse = soap_get___ns1__markTaskOpenedResponse(soap, NULL, "-ns1:markTaskOpenedResponse", "ns1:markTaskOpenedResponse");
	if (!soap_tmp___ns1__markTaskOpenedResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ns1__markTaskOpenedResponse_ && soap_tmp___ns1__markTaskOpenedResponse->ns1__markTaskOpenedResponse_)
		*ns1__markTaskOpenedResponse_ = *soap_tmp___ns1__markTaskOpenedResponse->ns1__markTaskOpenedResponse_;
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::removeProcesses(const char *endpoint, const char *soap_action, ns1__removeProcesses *ns1__removeProcesses_, ns1__removeProcessesResponse *ns1__removeProcessesResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__removeProcesses soap_tmp___ns1__removeProcesses;
	struct __ns1__removeProcessesResponse *soap_tmp___ns1__removeProcessesResponse;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__removeProcesses.ns1__removeProcesses_ = ns1__removeProcesses_;
	soap_serializeheader(soap);
	soap_serialize___ns1__removeProcesses(soap, &soap_tmp___ns1__removeProcesses);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__removeProcesses(soap, &soap_tmp___ns1__removeProcesses, "-ns1:removeProcesses", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__removeProcesses(soap, &soap_tmp___ns1__removeProcesses, "-ns1:removeProcesses", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__removeProcessesResponse_)
		return soap_closesock(soap);
	ns1__removeProcessesResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___ns1__removeProcessesResponse = soap_get___ns1__removeProcessesResponse(soap, NULL, "-ns1:removeProcessesResponse", "ns1:removeProcessesResponse");
	if (!soap_tmp___ns1__removeProcessesResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ns1__removeProcessesResponse_ && soap_tmp___ns1__removeProcessesResponse->ns1__removeProcessesResponse_)
		*ns1__removeProcessesResponse_ = *soap_tmp___ns1__removeProcessesResponse->ns1__removeProcessesResponse_;
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::startProcessWS(const char *endpoint, const char *soap_action, ns1__startProcessWS *ns1__startProcessWS_, ns1__startProcessWSResponse *ns1__startProcessWSResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__startProcessWS soap_tmp___ns1__startProcessWS;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__startProcessWS.ns1__startProcessWS_ = ns1__startProcessWS_;
	soap_serializeheader(soap);
	soap_serialize___ns1__startProcessWS(soap, &soap_tmp___ns1__startProcessWS);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__startProcessWS(soap, &soap_tmp___ns1__startProcessWS, "-ns1:startProcessWS", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__startProcessWS(soap, &soap_tmp___ns1__startProcessWS, "-ns1:startProcessWS", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__startProcessWSResponse_)
		return soap_closesock(soap);
	ns1__startProcessWSResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__startProcessWSResponse_->soap_get(soap, "ns1:startProcessWSResponse", "ns1:startProcessWSResponse");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServerAPIBindingProxy::updateVariablesWS(const char *endpoint, const char *soap_action, ns1__updateVariablesWS *ns1__updateVariablesWS_, ns1__updateVariablesWSResponse *ns1__updateVariablesWSResponse_)
{	struct soap *soap = this->soap;
	struct __ns1__updateVariablesWS soap_tmp___ns1__updateVariablesWS;
	struct __ns1__updateVariablesWSResponse *soap_tmp___ns1__updateVariablesWSResponse;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/AuthenticationServiceBean http://rtwf:8888/runawfe-wfe-service-4.1.1-SNAPSHOT/ExecutionServiceBean";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__updateVariablesWS.ns1__updateVariablesWS_ = ns1__updateVariablesWS_;
	soap_serializeheader(soap);
	soap_serialize___ns1__updateVariablesWS(soap, &soap_tmp___ns1__updateVariablesWS);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__updateVariablesWS(soap, &soap_tmp___ns1__updateVariablesWS, "-ns1:updateVariablesWS", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__updateVariablesWS(soap, &soap_tmp___ns1__updateVariablesWS, "-ns1:updateVariablesWS", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__updateVariablesWSResponse_)
		return soap_closesock(soap);
	ns1__updateVariablesWSResponse_->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___ns1__updateVariablesWSResponse = soap_get___ns1__updateVariablesWSResponse(soap, NULL, "-ns1:updateVariablesWSResponse", "ns1:updateVariablesWSResponse");
	if (!soap_tmp___ns1__updateVariablesWSResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ns1__updateVariablesWSResponse_ && soap_tmp___ns1__updateVariablesWSResponse->ns1__updateVariablesWSResponse_)
		*ns1__updateVariablesWSResponse_ = *soap_tmp___ns1__updateVariablesWSResponse->ns1__updateVariablesWSResponse_;
	return soap_closesock(soap);
}
/* End of client proxy code */
